const dummyDMData = [
  {
    name: "John Doe",
    id: "@johndoe1",
    message: "Hey, how's it going? I hope you're having a great day!",
    tweetTime: "5h",
    status: "new",
  },
  {
    name: "Alice Smith",
    id: "@alicesmith2",
    message: "I'm doing well, thanks! I had a relaxing weekend, how about you?",
    tweetTime: "2d",
    status: "new",
  },
  {
    name: "Bob Johnson",
    id: "@bobjohnson3",
    message: "Had a great day today! Went to the park and played some sports.",
    tweetTime: "1h",
    status: "new",
  },
  {
    name: "Charlie Brown",
    id: "@charliebrown4",
    message: "I went hiking in the mountains and saw some breathtaking views.",
    tweetTime: "8h",
    status: "read",
  },
  {
    name: "Eva White",
    id: "@evawhite5",
    message: "Spent the weekend hiking and reconnecting with nature. It was amazing!",
    tweetTime: "6h",
    status: "read",
  },
  {
    name: "David Lee",
    id: "@davidlee6",
    message: "Just finished a great book. It's always bittersweet when a good story ends.",
    tweetTime: "9h",
    status: "read",
  },
  {
    name: "Grace Taylor",
    id: "@gracetaylor7",
    message: "Had a fantastic dinner with friends last night. Good food, good company!",
    tweetTime: "7h",
    status: "read",
  },
  {
    name: "Michael Clark",
    id: "@michaelclark8",
    message: "Heading to the gym for a workout. Working on those fitness goals!",
    tweetTime: "4h",
    status: "read",
  },
  {
    name: "Olivia Brown",
    id: "@oliviabrown9",
    message: "I watched the sunset at the beach. What a beautiful evening!",
    tweetTime: "10h",
    status: "read",
  },
  {
    name: "Sophia Davis",
    id: "@sophiadavis10",
    message: "Just adopted a cute puppy named Max. He's adorable!",
    tweetTime: "12h",
    status: "read",
  },
  {
    name: "Liam Wilson",
    id: "@liamwilson11",
    message: "I cooked a delicious homemade meal tonight. Chef mode on!",
    tweetTime: "3h",
    status: "read",
  },
  {
    name: "Ava Martin",
    id: "@avamartin12",
    message: "Exploring new places in the city. There's so much to see!",
    tweetTime: "6h",
    status: "read",
  },
  {
    name: "Noah Johnson",
    id: "@noahjohnson13",
    message: "Just started a new hobby - painting. It's so relaxing!",
    tweetTime: "8h",
    status: "read",
  },
  {
    name: "Isabella Martinez",
    id: "@isabellamartinez14",
    message: "Attended a live music concert last night. The energy was incredible!",
    tweetTime: "11h",
    status: "read",
  },
  {
    name: "James Smith",
    id: "@jamessmith15",
    message: "Enjoying a lazy Sunday at home with a good movie.",
    tweetTime: "7h",
    status: "read",
  },
  {
    name: "Mia Johnson",
    id: "@miajohnson16",
    message: "Spent the day at the zoo. The animals were adorable!",
    tweetTime: "9h",
    status: "read",
  },
  {
    name: "Benjamin Wilson",
    id: "@benjaminwilson17",
    message: "Trying out a new recipe for dinner tonight. Fingers crossed!",
    tweetTime: "5h",
    status: "read",
  },
  {
    name: "Charlotte Davis",
    id: "@charlottedavis18",
    message: "Saw a stunning rainbow after the rain. Nature's beauty never ceases to amaze me!",
    tweetTime: "4h",
    status: "read",
  },
  {
    name: "William White",
    id: "@williamwhite19",
    message: "Just finished a great book. It's always bittersweet when a good story ends.",
    tweetTime: "10h",
    status: "read",
  },
];

export default dummyDMData;
