const communityGroups = [
    { id: 1, title: "Tech Enthusiasts", members: 170 },
    { id: 2, title: "Food Lovers", members: 809 },
    { id: 3, title: "Fitness Freaks", members: 674 },
    { id: 4, title: "Photography Club", members: 452 },
    { id: 5, title: "Bookworms", members: 312 },
    { id: 6, title: "Artists Collective", members: 235 },
    { id: 7, title: "Movie Buffs", members: 567 },
    { id: 8, title: "Travelers Club", members: 721 },
    { id: 9, title: "Gaming Guild", members: 189 },
    { id: 10, title: "Fashionistas", members: 524 },
    { id: 11, title: "Nature Explorers", members: 398 },
    { id: 12, title: "Music Lovers", members: 653 },
    { id: 13, title: "Cooking Crew", members: 276 },
    { id: 14, title: "Sports Fans", members: 489 },
    { id: 15, title: "Pet Owners", members: 125 },
    { id: 16, title: "Yoga Enthusiasts", members: 572 },
    { id: 17, title: "Film Makers", members: 207 },
    { id: 18, title: "Environmentalists", members: 345 },
    { id: 19, title: "Business Network", members: 618 },
    { id: 20, title: "DIY Crafters", members: 143 },
    { id: 21, title: "Anime Fans", members: 398 },
    { id: 22, title: "Science Geeks", members: 541 },
    { id: 23, title: "Startup Enthusiasts", members: 789 },
    { id: 24, title: "Fitness Moms", members: 432 },
    { id: 25, title: "Hiking Club", members: 275 },
  ];
  
  export default communityGroups;
  